const express = require('express');
const router = express.Router();
const productController = require('../controllers/productController');
const authJwt = require('../middlewares/authJwt');
router.get('/id', productController.getOneProductById);
router.post('/add', authJwt.authUser, authJwt.isAdmin, productController.addProduct);
router.patch('/update', authJwt.authUser, authJwt.isAdmin, productController.updateProduct);
router.get('/search', productController.getProductsByName);
router.get('/statistic', productController.statisticPro);
router.use('/:slug', productController.getByType);
router.get('/', productController.getAll);
module.exports = router;